export const FETCH_ALL_TOUR_START = 'FETCH_ALL_TOUR_START';
export const FETCH_ALL_TOUR_SUCCESS = 'FETCH_ALL_TOUR_SUCCESS';
export const FETCH_ALL_TOUR_FAILED = 'FETCH_ALL_TOUR_FAILED';
export const FETCH_TOUR_START = 'FETCH_TOUR_START';
export const FETCH_TOUR_SUCCESS = 'FETCH_TOUR_SUCCESS';
export const FETCH_TOUR_FAILED = 'FETCH_TOUR_FAILED';
export const FETCH_USER_TOURS = 'FETCH_USER_TOURS';

export const USER_SIGNUP_START = 'USER_SIGNUP_START';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';
export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';

export const USER_UPDATE_START = 'USER_UPDATE_START';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_SETTINGS = 'USER_UPDATE_SETTINGS';
export const USER_UPDATE_PASSWORD = 'USER_UPDATE_PASSWORD';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const BOOK_TOUR_START = 'BOOK_TOUR_START';
export const BOOK_TOUR_SUCCESS = 'BOOK_TOUR_SUCCESS';
export const BOOK_TOUR_FAIL = 'BOOK_TOUR_FAIL';

export const FETCH_USER_BOOKING_TOURS = 'FETCH_USER_BOOKING_TOURS';

export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const FETCH_REVIEWS_START = 'FETCH_REVIEWS_START';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAIL = 'FETCH_REVIEWS_FAIL';
